### PR TITLE
New translations for translation/fr/site/interface_translation-fr-site

### PR DESCRIPTION
**Pull request by sc-translatatron**
Request made by noeismet

Please do not modify this branch directly. Changes should be
made via the Bilara Translation App and the Pull Request
updated from Bilara.

### CODE REVIEW

**Comment by noeismet** [comment]
Ah, my apologies, I forgot another change, may you please ignore.

**Comment by noeismet** [comment]
@ccronje, it appears that the moment you edit a section, it automatically adds a space at the end of the section, even if I edited elsewhere in the section, is that problematic? Should I make sure to remove that space?

**Comment by ccronje** [comment]
@noeismet I believe it's the Nilakkhana script that adds a space automatically, so all good. Double-checking with the team and will let you know if there's any problem.

**Comment by ccronje** [comment]
@noeismet Bhante added: Any segment should end with a space, except segments that end with an em-dash —. Em-dash does not take spaces either side.

**Comment by noeismet** [comment]
@ccronje, excellent, thanks so much for checking

**Pull request merged**
