### PR TITLE
Fix segments

### PR DESCRIPTION
**Pull request by alple**

### CODE REVIEW

**Comment by sabbamitta** [comment]
Hi Alek, I am a bit confused about this. Just checking for an3.102 because this is one I have already translated. The segments you want to delete, an3.102:4.3 and an3.102:4.4 do have content in translation, both in English and in German. Should they still be deleted?

**Comment by alple** [comment]
Hey, as @sujato wrote: 

> I guess in many cases if there is no content we simply omit the relevant segment, eg. in the comments or the references. So let;s do the same with these cases:
> If there is no content, omit the segment rather than retaining an empty segment.

But now we see that it will create some hiccups in the root numbering. I'll just remove the empty spaces and leave the uids for now.

**Comment by sabbamitta** [comment]
Thanks for your attention.

I was told to put a space into a segment that stays empty in translation (these are segments that have text in the root segment). Now I am confused and not sure what to do.

The trouble is, if I don't type anything into a segment and really leave it really very empty empty, Bilara won't create a segment for that, and in GitHub the translation text will end up with less segments than the root text, and all IDs are messed up…

**Comment by alple** [comment]
@sujato any insights into that?
I think we should make the whitespace consistent. You can find `" "` as well as `""` in the code, so one way or the other.

**Comment by sabbamitta** [comment]
In Bilara I can't type `""`. If I don't type anything it won't show up as `""`, but there will just be no segment at all, no segment ID, just nothing. When I type a space it will show up as `" "` with the correct ID.

Another option would be, if having `""` is important for some reason, to make Bilara show `""` if the translator leaves the segment empty. But that would be extra work.

**Comment by sujato** [comment]
> I was told to put a space into a segment that stays empty in translation (these are segments that have text in the root segment). Now I am confused and not sure what to do.
> 
> The trouble is, if I don't type anything into a segment and really leave it really very empty empty, Bilara won't create a segment for that, and in GitHub the translation text will end up with less segments than the root text, and all IDs are messed up…

You shouldn't have to think about what Bilara does. Just write what you want to write, and let Bilara worry about keeping it all straight.

I'm not sure what advice you've had, but Bilara doesn't care if you enter anything in a segment or not. Blank segments don't affect segment numbering. Segment numbers are fixed, Bilara doesn't touch them. All it does is says *this* segment has *this* content. Whether the content is a string of text or nothing at all is irrelevant.

**Pull request merged**
