### PR TITLE
Second try localizing new items

### PR DESCRIPTION
**Pull request by thesunshade**
This PR is needed for https://github.com/suttacentral/suttacentral/pull/3241

Add:
home:22
home:23
home:24.1
home:24.2
home:24.3
footer:byHumans
footer:allWork

Delete
home:21
home:22
home:23
home:24.1
home:24.2
home:24.3

### CODE REVIEW

**Comment by sabbamitta** [comment]
Why does this pull request contain many files by various translators? @thesunshade

**Comment by thesunshade** [comment]
I have absolutely no idea and it's quite frustrating. 

HongDa is taking care of it.

**Comment by sabbamitta** [comment]
I can't tell for the other translators, but the changes in the files by sabbamitta have not been published yet. @ihongda

**Comment by ccronje** [comment]
It looks like all the changes on the `unpublished` branch. I recommend closing this and trying the manual publication process for the specific files you want to update https://github.com/suttacentral/bilara-data/wiki/Manual-publication-workflow

**Comment by thesunshade** [comment]
> I recommend closing this and trying the manual publication process for the specific files you want to update

Hongda is already working on this. Please don't delete my branch.

**Comment by thesunshade** [comment]
I re-opend this to make sure it doesn't get deleted. HongDa can close once he has taken care of it.

**Pull request closed without merging**
