### PR TITLE
New translations for translation/en/soma/sutta/kn/thig

### PR DESCRIPTION
**Pull request by sc-translatatron**
Request made by ayyasoma

Please do not modify this branch directly. Changes should be
made via the Bilara Translation App and the Pull Request
updated from Bilara.

### CODE REVIEW

**Comment by ccronje** [comment]
@ayyasoma please see https://github.com/suttacentral/bilara-data/wiki/SuttaCentral-translation-style-guide

Replace dot-dot-dot with ellipsis (https://unicode-table.com/en/2026/) in the following texts and segments:
thig1.18
2.1
thig10.1
12.1
thig11.1
13.1
thig2.10
3.1
thig3.8
4.1
thig4.1
5.1
thig5.12
6.1
thig6.1
7.1
thig6.8
7.1
thig7.3
8.1
thig8.1
9.1
thig9.1
10.1

Replace double straight quotations with curly (https://unicode-table.com/en/201C/, https://unicode-table.com/en/201D/) in the following texts and segments:
thig13.5
25.4
26.1
28.4
thig16.1
31.4

There are a number of straight apostrophes - please check and use https://unicode-table.com/en/2019/

If you would like me to fix please let me know.

Thank you!

**Comment by ayyasoma** [comment]
Dear Carmi,

Thank you for your note and apologies for missing the below. 

If you could change all the below it would be great!

Let me know.

With mettā,

Ayyā Somā
Co-Founder of Buddhist Insights 
and Empty Cloud Monastery

www.buddhistinsights.com
www.emptycloud.org
***@***.***

**Comment by ayyasoma** [comment]
Actually I am taking care of it now, so I will hit publish again once I finish :)

With mettā,

Ayyā Somā
Co-Founder of Buddhist Insights 
and Empty Cloud Monastery

www.buddhistinsights.com
www.emptycloud.org
***@***.***

**Comment by ayyasoma** [comment]
Dear Carmi,

Everything has been corrected. :)
Hopefully I didn’t miss anything this time around. 

Thank you for your help!

**Pull request closed without merging**
