### PR TITLE
Updates (primarily to refer to the six inner sources with names that differentiate from the six organs)

### PR DESCRIPTION
**Pull request by abd3**
This convention was adopted by Dr. Lee Joongpyo to help clarify that when we talk about abandoning the eye, etc. we're not talking about abandoning the eye organ

### CODE REVIEW

**Comment by sabbamitta** [comment]
It seems [a number of files](https://github.com/suttacentral/bilara-data/tree/unpublished/translation/en/davis/sutta/kn/dhp) has been added to the "davis" folder that end in `_translation-en-sujato.json`. This seems confusing and  misleading to me, but maybe there is some purpose behind it?

**Comment by ccronje** [comment]
Thanks for letting us know Ayya @sabbamitta. [The files](https://github.com/suttacentral/bilara-data/tree/unpublished/translation/en/davis/sutta/kn/dhp) aren't showing in Bilara. @abd3 you'll need to change the filename to see them.

**Comment by abd3** [comment]
Whoops! I moved those files in for modification and neglected to update the name. I'll correct.

**Comment by abd3** [comment]
I've submitted the [pull request to correct this](https://github.com/suttacentral/bilara-data/pull/2685).

**Pull request merged**
